### PR TITLE
SoapKit doesn't compile through CocoaPods

### PR DESCRIPTION
**Pull request by pilot34**
Headers are inside a folder, so we should include this folder in an umbrella header

### CODE REVIEW

**Comment by hons82** [comment]
Thanks. I've developed this for my former employer.
Currently I'm not using it, so I haven't been aware.

THX again

**Comment by pilot34** [comment]
Thx for open-sourcing it. Very helpful!

**Comment by hons82** [comment]
Hope to be able to come back to it soon…

Are you using it in a productive environment?

**Comment by pilot34** [comment]
Not yet, but will.

I forked it, because I need some custom error handling and so on.

**Pull request merged**
